### ISSUE TITLE
[BUG]: u.getCurrentUser is not a function

### ISSUE THREAD

**Issue by notdylandover** [Friedshrimp-Studio-TW/Discord-Experiments#6]
### Describe the bug | BUG描述

TypeError: u.getCurrentUser is not a function
    at discordExperiments.start (DeveloperExperiments.plugin.js:23:9)
    at A.startPlugin (renderer.js:5:34290)
    at A.startAddon (renderer.js:5:34083)
    at A.loadAddon (renderer.js:5:6780)
    at A.loadAddon (renderer.js:5:31500)
    at A.reloadAddon (renderer.js:5:7276)
    at AsyncFunction.<anonymous> (renderer.js:5:4400)

### Version | 版本

V1.5.0

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過

**Comment by VincentX0905** [comment]
It working fine for me.
Note: This plugins just support discord stable version
![image](https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/76867533/4cfec6a5-7c8d-43d2-a3d4-82fd680a86ec)
